name: pyci

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: |
          pip install uv
          make install
          
      - run: make build
      - run: make package-install
      - run: make test
      - run: make test-coverage
      - run: make lint