name: pyci

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: make install
      - run: make build
      - run: make package-install
      - run: make test
      - run: make test-coverage
      - run: make lint
      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=hexlet-boilerplates_python-package
            -Dsonar.organization=hexlet-boilerplates
            -Dsonar.python.coverage.reportPaths=coverage.xml